# config.yml
excluded_directories:
  - .venv
  - venv
  - node_modules
  - git

desired_extensions:
  - .py
  - .js
  - .css
  - .html
  - .sh
  - .c
  - .cpp
  - .yml

specific_files:
  - Dockerfile
  - .gitignore
